CREATE TABLE IF NOT EXISTS "person"
(
    "id"            INTEGER PRIMARY KEY generated by default as identity,
    "name"          VARCHAR(255) NOT NULL,
    "gender"        VARCHAR(6)   NOT NULL,
    "date_of_birth" DATE         NOT NULL,
    "is_gravid"     BOOLEAN      NOT NULL DEFAULT false
);


CREATE TABLE IF NOT EXISTS "indicator"
(
    "id"        INTEGER PRIMARY KEY generated by default as identity,
    "eng_name"  VARCHAR(255) NOT NULL,
    "rus_name"  VARCHAR(255) NOT NULL,
    "gender"    VARCHAR(6)   NOT NULL,
    "is_gravid" BOOLEAN      NOT NULL DEFAULT false,
    "min_age"   INTEGER      NOT NULL,
    "max_age"   INTEGER      NOT NULL,
    "min_value" FLOAT(53)    NOT NULL,
    "max_value" FLOAT(53)    NOT NULL,
    "units"     VARCHAR(50)  NOT NULL DEFAULT 'standart'
);

CREATE TABLE "indicator_group"
(
    id         integer                NOT NULL,
    group_name character varying(255) NOT NULL,
    indicators text[]
);


CREATE TABLE IF NOT EXISTS "transcript"
(
    "id"     INTEGER PRIMARY KEY generated by default as identity,
    "name"   VARCHAR(255) NOT NULL,
    "gender" VARCHAR(6)   NOT NULL
);

CREATE TABLE IF NOT EXISTS "referent"
(
    "id"            INTEGER PRIMARY KEY generated by default as identity,
    "current_value" FLOAT(53)    NOT NULL,
    "reg_date"      DATE         NOT NULL,
    "status"        VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "referent_transcript"
(
    "referent_id"   INTEGER REFERENCES referent (id)   ON DELETE CASCADE,
    "transcript_id" INTEGER REFERENCES transcript (id) ON DELETE NO ACTION,
    PRIMARY KEY ("referent_id", "transcript_id")
);

CREATE TABLE IF NOT EXISTS "reason"
(
    "id"   INTEGER PRIMARY KEY generated by default as identity,
    "name" VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS "fall_reason"
(
    "transcript_id" INTEGER REFERENCES transcript (id) ON DELETE NO ACTION,
    "reason_id"     INTEGER REFERENCES reason (id)     ON DELETE NO ACTION,
    PRIMARY KEY ("transcript_id", "reason_id")
);

CREATE TABLE IF NOT EXISTS "raise_reason"
(
    "transcript_id" INTEGER REFERENCES transcript (id) ON DELETE NO ACTION,
    "reason_id"     INTEGER REFERENCES reason (id)     ON DELETE NO ACTION,
    PRIMARY KEY ("transcript_id", "reason_id")
);


CREATE TABLE IF NOT EXISTS "excluded_reason"
(
    "person_id" INTEGER REFERENCES person (id) ON DELETE CASCADE   NOT NULL,
    "reason_id" INTEGER REFERENCES reason (id) ON DELETE NO ACTION NOT NULL,
    PRIMARY KEY ("person_id", "reason_id")
);


CREATE TABLE IF NOT EXISTS "measure"
(
    "id"           INTEGER PRIMARY KEY generated by default as identity,
    "person_id"    INTEGER REFERENCES Person (id)                     NOT NULL,
    "indicator_id" INTEGER REFERENCES Indicator (id)                  NOT NULL,
    "referent_id"  INTEGER REFERENCES Referent (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE "unit"
(
    "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(50) NOT NULL
);