INSERT INTO public.reason (id, name) VALUES (1, 'дефицит ванадия');
INSERT INTO public.reason (id, name) VALUES (2, 'передозировка рыбьего жира');
INSERT INTO public.reason (id, name) VALUES (3, 'избыточное поступление с воздухом меди');
INSERT INTO public.reason (id, name) VALUES (4, 'панкреатит');
INSERT INTO public.reason (id, name) VALUES (5, 'гипогонадизм');
INSERT INTO public.reason (id, name) VALUES (6, 'болезнь Пламмера');
INSERT INTO public.reason (id, name) VALUES (7, 'гиперфункциональность почек');
INSERT INTO public.reason (id, name) VALUES (8, 'нарушение работы поджелудочной железы');
INSERT INTO public.reason (id, name) VALUES (9, 'гипергидратация');
INSERT INTO public.reason (id, name) VALUES (10, 'киста желтого тела');
INSERT INTO public.reason (id, name) VALUES (11, 'показатель гипоксии');
INSERT INTO public.reason (id, name) VALUES (12, 'повышенное использование витамина в организме');
INSERT INTO public.reason (id, name) VALUES (13, 'сахарный диабет');
INSERT INTO public.reason (id, name) VALUES (14, 'переутомление');
INSERT INTO public.reason (id, name) VALUES (15, 'отсутствие сна');
INSERT INTO public.reason (id, name) VALUES (16, 'избыток белка');
INSERT INTO public.reason (id, name) VALUES (17, 'передозировка гормонов щитовидной железы');
INSERT INTO public.reason (id, name) VALUES (18, 'генетические мутации, нарушающие обмен В12 в организме');
INSERT INTO public.reason (id, name) VALUES (19, 'истинная полицитемия');
INSERT INTO public.reason (id, name) VALUES (20, 'низкий кортизол');
INSERT INTO public.reason (id, name) VALUES (21, 'низкое содержание йода в пище');
INSERT INTO public.reason (id, name) VALUES (22, 'искусственная гипогликемия');
INSERT INTO public.reason (id, name) VALUES (23, 'диффузный токсический зоб');
INSERT INTO public.reason (id, name) VALUES (24, 'передозировка витамина D');
INSERT INTO public.reason (id, name) VALUES (25, 'аллергия');
INSERT INTO public.reason (id, name) VALUES (26, 'применение тиреостатиков');
INSERT INTO public.reason (id, name) VALUES (27, 'нарушение работы надпочечников');
INSERT INTO public.reason (id, name) VALUES (28, 'скрытые кровопотери');
INSERT INTO public.reason (id, name) VALUES (29, 'ослабленный иммунитет');
INSERT INTO public.reason (id, name) VALUES (30, 'избыток метионина');
INSERT INTO public.reason (id, name) VALUES (31, 'стресс');
INSERT INTO public.reason (id, name) VALUES (32, 'высокий инсулин');
INSERT INTO public.reason (id, name) VALUES (33, 'язвы в желудке');
INSERT INTO public.reason (id, name) VALUES (34, 'нарушение работы гипоталамуса');
INSERT INTO public.reason (id, name) VALUES (35, 'гепатиты');
INSERT INTO public.reason (id, name) VALUES (36, 'явные кровопотери');
INSERT INTO public.reason (id, name) VALUES (37, 'доброкачественная нейтропения детского возраста');
INSERT INTO public.reason (id, name) VALUES (38, 'избыточное поступление с водой меди');
INSERT INTO public.reason (id, name) VALUES (39, 'передозировка витамина С');
INSERT INTO public.reason (id, name) VALUES (40, 'повышенная функция паращитовидных желез');
INSERT INTO public.reason (id, name) VALUES (41, 'гипохлоргидрия');
INSERT INTO public.reason (id, name) VALUES (42, 'тиреоидит Хашимото');
INSERT INTO public.reason (id, name) VALUES (43, 'синдром Пендреда');
INSERT INTO public.reason (id, name) VALUES (44, 'менструация');
INSERT INTO public.reason (id, name) VALUES (45, 'изменение регуляции метаболизма йода в организме');
INSERT INTO public.reason (id, name) VALUES (46, 'избыток гормона роста');
INSERT INTO public.reason (id, name) VALUES (47, 'дефицит эстрогена');
INSERT INTO public.reason (id, name) VALUES (48, 'нарушение работы печени');
INSERT INTO public.reason (id, name) VALUES (49, 'себорея');
INSERT INTO public.reason (id, name) VALUES (50, 'дефицит омега-3');
INSERT INTO public.reason (id, name) VALUES (51, 'дефицит белка');
INSERT INTO public.reason (id, name) VALUES (52, 'инъекции В12 в последние 2 месяца');
INSERT INTO public.reason (id, name) VALUES (53, 'повышение фибриногена');
INSERT INTO public.reason (id, name) VALUES (54, 'рвота');
INSERT INTO public.reason (id, name) VALUES (55, 'инфекционный процесс');
INSERT INTO public.reason (id, name) VALUES (56, 'дефицит кальция');
INSERT INTO public.reason (id, name) VALUES (57, 'дефицит витамина А');
INSERT INTO public.reason (id, name) VALUES (58, 'апластическая анемия');
INSERT INTO public.reason (id, name) VALUES (59, 'повышение ферритина');
INSERT INTO public.reason (id, name) VALUES (60, 'пониженная функция паращитовидных желез');
INSERT INTO public.reason (id, name) VALUES (61, 'приём эстрогенов');
INSERT INTO public.reason (id, name) VALUES (62, 'холестаз');
INSERT INTO public.reason (id, name) VALUES (63, 'снижение альбумина');
INSERT INTO public.reason (id, name) VALUES (64, 'ревматоидный артрит');
INSERT INTO public.reason (id, name) VALUES (65, 'дефицит йода');
INSERT INTO public.reason (id, name) VALUES (66, 'простатит');
INSERT INTO public.reason (id, name) VALUES (67, 'поликистоз яичников');
INSERT INTO public.reason (id, name) VALUES (68, 'прием ОК');
INSERT INTO public.reason (id, name) VALUES (69, 'лечение антибиотиками');
INSERT INTO public.reason (id, name) VALUES (70, 'дефицит витамина B6');
INSERT INTO public.reason (id, name) VALUES (71, 'дефицит витамина B9');
INSERT INTO public.reason (id, name) VALUES (72, 'нарушение образования внутреннего фактора Касла');
INSERT INTO public.reason (id, name) VALUES (73, 'прием антигипертензивных средств группы ИАПФ');
INSERT INTO public.reason (id, name) VALUES (74, 'дефицит витамина B2');
INSERT INTO public.reason (id, name) VALUES (75, 'повышение церулоплазмина');
INSERT INTO public.reason (id, name) VALUES (76, 'гемолиз эритроцитов при заборе крови');
INSERT INTO public.reason (id, name) VALUES (77, 'повышение эритроцитов');
INSERT INTO public.reason (id, name) VALUES (78, 'дефицит витамина B1');
INSERT INTO public.reason (id, name) VALUES (79, 'дисбактериоз');
INSERT INTO public.reason (id, name) VALUES (80, 'избыток поступления с пищей фосфора');
INSERT INTO public.reason (id, name) VALUES (81, 'нарушение всасываемости');
INSERT INTO public.reason (id, name) VALUES (82, 'гипохромная анемия');
INSERT INTO public.reason (id, name) VALUES (83, 'курение');
INSERT INTO public.reason (id, name) VALUES (84, 'вирусная инфекция');
INSERT INTO public.reason (id, name) VALUES (85, 'послеродовый тиреоидит');
INSERT INTO public.reason (id, name) VALUES (86, 'прием препаратов с высокими дозами В12');
INSERT INTO public.reason (id, name) VALUES (87, 'высокий уровень окислительного стресса');
INSERT INTO public.reason (id, name) VALUES (88, 'целиакия');
INSERT INTO public.reason (id, name) VALUES (89, 'гормональные нарушения');
INSERT INTO public.reason (id, name) VALUES (90, 'дефицит витамина C');
INSERT INTO public.reason (id, name) VALUES (91, 'приём КОК');
INSERT INTO public.reason (id, name) VALUES (92, 'недостаточность надпочечников');
INSERT INTO public.reason (id, name) VALUES (93, 'беременность');
INSERT INTO public.reason (id, name) VALUES (94, 'дефицит глутатиона');
INSERT INTO public.reason (id, name) VALUES (95, 'недостаток меди в пище');
INSERT INTO public.reason (id, name) VALUES (96, 'алкалоз');
INSERT INTO public.reason (id, name) VALUES (97, 'гиперхромная анемия');
INSERT INTO public.reason (id, name) VALUES (98, 'дефицит витамина D');
INSERT INTO public.reason (id, name) VALUES (99, 'паразитоз');
INSERT INTO public.reason (id, name) VALUES (100, 'первые 6-8 недель терапии препаратами железа');
INSERT INTO public.reason (id, name) VALUES (101, 'диарея');
INSERT INTO public.reason (id, name) VALUES (102, 'недостаточное поступление с пищей');
INSERT INTO public.reason (id, name) VALUES (103, 'пожилой возраст');
INSERT INTO public.reason (id, name) VALUES (104, 'приём глюкокортикоидов');
INSERT INTO public.reason (id, name) VALUES (105, 'талассемия');
INSERT INTO public.reason (id, name) VALUES (106, 'воспалительный процесс');
INSERT INTO public.reason (id, name) VALUES (107, 'избыток пролактина');
INSERT INTO public.reason (id, name) VALUES (108, 'дефицит инозитола');
INSERT INTO public.reason (id, name) VALUES (109, 'прием лекарств для снижения давления');
INSERT INTO public.reason (id, name) VALUES (110, 'почечная недостаточность');
INSERT INTO public.reason (id, name) VALUES (111, 'повышение альдостерона');
INSERT INTO public.reason (id, name) VALUES (112, 'вегетарианство');
INSERT INTO public.reason (id, name) VALUES (113, 'снижение эритроцитов');
INSERT INTO public.reason (id, name) VALUES (114, 'дефицит селена');
INSERT INTO public.reason (id, name) VALUES (115, 'избыток андрогенов');
INSERT INTO public.reason (id, name) VALUES (116, 'гематологические заболевания');
INSERT INTO public.reason (id, name) VALUES (117, 'лимфома');
INSERT INTO public.reason (id, name) VALUES (118, 'опухоли');
INSERT INTO public.reason (id, name) VALUES (119, 'повышенное потоотделение');
INSERT INTO public.reason (id, name) VALUES (120, 'изменение формы эритроцитов');
INSERT INTO public.reason (id, name) VALUES (121, 'низкий уровень ДГЭА-С');
INSERT INTO public.reason (id, name) VALUES (122, 'метаболический синдром');
INSERT INTO public.reason (id, name) VALUES (123, 'нарушение работы почек');
INSERT INTO public.reason (id, name) VALUES (124, 'катаболизм');
INSERT INTO public.reason (id, name) VALUES (125, 'бактериальная инфекция');
INSERT INTO public.reason (id, name) VALUES (126, 'дефицит бетаина');
INSERT INTO public.reason (id, name) VALUES (127, 'инфекция Helicobacter pylori');
INSERT INTO public.reason (id, name) VALUES (128, 'увеличение селезёнки');
INSERT INTO public.reason (id, name) VALUES (129, 'бессолевая диета');
INSERT INTO public.reason (id, name) VALUES (130, 'состояние кетоза');
INSERT INTO public.reason (id, name) VALUES (131, 'прием стероидных гормонов');
INSERT INTO public.reason (id, name) VALUES (132, 'избыток кофе в рационе');
INSERT INTO public.reason (id, name) VALUES (133, 'повышение альбумина');
INSERT INTO public.reason (id, name) VALUES (134, 'физическом перенапряжении');
INSERT INTO public.reason (id, name) VALUES (135, 'дефицит метионина');
INSERT INTO public.reason (id, name) VALUES (136, 'дефицит витамина B12');
INSERT INTO public.reason (id, name) VALUES (137, 'атеросклероз');
INSERT INTO public.reason (id, name) VALUES (138, 'нарушение обмена веществ');
INSERT INTO public.reason (id, name) VALUES (139, 'приём некоторых лекарственных препаратов');
INSERT INTO public.reason (id, name) VALUES (140, 'период активного роста у ребёнка');
INSERT INTO public.reason (id, name) VALUES (141, 'врождённый дефицит лептина');
INSERT INTO public.reason (id, name) VALUES (142, 'мутация гена MTHFR');
INSERT INTO public.reason (id, name) VALUES (143, 'дефицит цинка');
INSERT INTO public.reason (id, name) VALUES (144, 'несбалансированная диета');
INSERT INTO public.reason (id, name) VALUES (145, 'псориаз');
INSERT INTO public.reason (id, name) VALUES (146, 'гемолитическая анемия');
INSERT INTO public.reason (id, name) VALUES (147, 'голодание');
INSERT INTO public.reason (id, name) VALUES (148, 'пониженное выделение кальция с мочой');
INSERT INTO public.reason (id, name) VALUES (149, 'обезвоживание');
INSERT INTO public.reason (id, name) VALUES (150, 'нарушение работы щитовидной железы');
INSERT INTO public.reason (id, name) VALUES (151, 'дефицит железа');
INSERT INTO public.reason (id, name) VALUES (152, 'избыток кальция');
INSERT INTO public.reason (id, name) VALUES (153, 'избыток фитоэстрогенов в рационе');
INSERT INTO public.reason (id, name) VALUES (154, 'избыток алюминия');
INSERT INTO public.reason (id, name) VALUES (155, 'длительный приём препаратов с магнием');
INSERT INTO public.reason (id, name) VALUES (156, 'дробное питание');
INSERT INTO public.reason (id, name) VALUES (157, 'дефицит марганца');
INSERT INTO public.reason (id, name) VALUES (158, 'микросфероцитоз');
INSERT INTO public.reason (id, name) VALUES (159, 'нарушение работы желчного системы');
INSERT INTO public.reason (id, name) VALUES (160, 'мальабсорбция');
INSERT INTO public.reason (id, name) VALUES (161, 'гиперфункциональность кишечника');
INSERT INTO public.reason (id, name) VALUES (162, 'нарушение работы гипофиза');
INSERT INTO public.reason (id, name) VALUES (163, 'злоупотребление БАДами');
INSERT INTO public.reason (id, name) VALUES (164, 'гипертиреоз');
INSERT INTO public.reason (id, name) VALUES (165, 'гиперпротеинемия');
INSERT INTO public.reason (id, name) VALUES (166, 'дефицит холина');
INSERT INTO public.reason (id, name) VALUES (167, 'генетика');
INSERT INTO public.reason (id, name) VALUES (168, 'дефицит фолатов');
INSERT INTO public.reason (id, name) VALUES (169, 'резкая потеря веса');
INSERT INTO public.reason (id, name) VALUES (170, 'прием пищи перед проведением анализа крови');
INSERT INTO public.reason (id, name) VALUES (171, 'повышение С-реактивного белка');
INSERT INTO public.reason (id, name) VALUES (172, 'аутоиммунный тиреоидит');
INSERT INTO public.reason (id, name) VALUES (173, 'избыток железа');
INSERT INTO public.reason (id, name) VALUES (174, 'нарушение работы эндокринной системы');
INSERT INTO public.reason (id, name) VALUES (175, 'инсулинорезистентность');
INSERT INTO public.reason (id, name) VALUES (176, 'недостаток в пище B9');
INSERT INTO public.reason (id, name) VALUES (177, 'гипергликемия');
INSERT INTO public.reason (id, name) VALUES (178, 'лейкоз');
INSERT INTO public.reason (id, name) VALUES (179, 'ацидоз');
INSERT INTO public.reason (id, name) VALUES (180, 'синдром Жильбера');
INSERT INTO public.reason (id, name) VALUES (181, 'избыток углеводов в рационе');
INSERT INTO public.reason (id, name) VALUES (182, 'дефицит хрома');
INSERT INTO public.reason (id, name) VALUES (183, 'снижение гематокрита');
INSERT INTO public.reason (id, name) VALUES (184, 'резистентность к андрогенам');
INSERT INTO public.reason (id, name) VALUES (185, 'высокий кортизол');
INSERT INTO public.reason (id, name) VALUES (186, 'эрозии в желудке');
INSERT INTO public.reason (id, name) VALUES (187, 'малоподвижный образ жизни');
INSERT INTO public.reason (id, name) VALUES (188, 'сердечная недостаточность');
INSERT INTO public.reason (id, name) VALUES (189, 'дефицит фосфора');
INSERT INTO public.reason (id, name) VALUES (190, 'болезни ЖКТ');
INSERT INTO public.reason (id, name) VALUES (191, 'глистная инвазия');
INSERT INTO public.reason (id, name) VALUES (192, 'заболевания крови');
INSERT INTO public.reason (id, name) VALUES (193, 'недостаточность желтого тела');
INSERT INTO public.reason (id, name) VALUES (194, 'гемохроматоз');
INSERT INTO public.reason (id, name) VALUES (195, 'избыток гомоцистеина');
INSERT INTO public.reason (id, name) VALUES (196, 'лептинорезистентность');
INSERT INTO public.reason (id, name) VALUES (197, 'увеличение содержания йода в пище');
INSERT INTO public.reason (id, name) VALUES (198, 'проблемы с усвоением железа в кишечнике');
INSERT INTO public.reason (id, name) VALUES (199, 'дефицит половых гормонов');
INSERT INTO public.reason (id, name) VALUES (200, 'избыточное поступление с воздухом цинка');
INSERT INTO public.reason (id, name) VALUES (201, 'дефицит меди');
INSERT INTO public.reason (id, name) VALUES (202, 'нарушение внутриклеточного обмена');
INSERT INTO public.reason (id, name) VALUES (203, 'гемахроматоз');
INSERT INTO public.reason (id, name) VALUES (204, 'избыток мясной пищи в рационе');
INSERT INTO public.reason (id, name) VALUES (205, 'дефицит магния');
INSERT INTO public.reason (id, name) VALUES (206, 'интоксикация');
INSERT INTO public.reason (id, name) VALUES (207, 'приём мочегонных препаратов');
INSERT INTO public.reason (id, name) VALUES (208, 'ожирение');
INSERT INTO public.reason (id, name) VALUES (209, 'гипопаратиреоз');
INSERT INTO public.reason (id, name) VALUES (210, 'передозировка витаминов фолиевой кислоты');
INSERT INTO public.reason (id, name) VALUES (211, 'нарушение работы тонкого кишечника');
INSERT INTO public.reason (id, name) VALUES (212, 'повышенный холестерин');
INSERT INTO public.reason (id, name) VALUES (213, 'гипотиреоз');
INSERT INTO public.reason (id, name) VALUES (214, 'новообразования');
INSERT INTO public.reason (id, name) VALUES (215, 'токсичные металлы');
INSERT INTO public.reason (id, name) VALUES (216, 'остеопороз');
INSERT INTO public.reason (id, name) VALUES (217, 'пониженная кислотность желудка');
INSERT INTO public.reason (id, name) VALUES (218, 'дефицит жиров в рационе');
INSERT INTO public.reason (id, name) VALUES (219, 'злоупотребление алкоголем');
INSERT INTO public.reason (id, name) VALUES (220, 'нарушения всасывания жиров');
INSERT INTO public.reason (id, name) VALUES (221, 'высокое артериальное давление');
