create table person(
                   id int primary key generated by default as identity,
                   name varchar(120) NOT NULL,
                   gender Varchar NOT NULL,
                   date_of_birth date NOT NULL
);

create table indicator(
                  id int primary key generated by default as identity,
                  name varchar(100) NOT NULL,
                  gender VARCHAR NOT NULL,
                  max_age int NOT NULL,
                  min_age int NOT NULL,
                  max_value numeric NOT NULL,
                  min_value numeric NOT NULL
);

create table person_indicator(
                 person_id int REFERENCES person(id),
                 indicator_id int REFERENCES indicator(id),
                 current_value numeric,
                 PRIMARY KEY (person_id, indicator_id)
);