SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    is_verified boolean NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    person_id bigint,
    CONSTRAINT customer_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('EDITOR'::character varying)::text, ('ADMIN'::character varying)::text]))),
    CONSTRAINT customer_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('ACTIVE'::character varying)::text])))
);


--
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: excluded_reason; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.excluded_reason (
    person_id bigint NOT NULL,
    reason_id integer NOT NULL
);


--
-- Name: fall_reason; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fall_reason (
    transcript_id integer NOT NULL,
    reason_id integer NOT NULL
);


--
-- Name: indicator; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.indicator (
    id integer NOT NULL,
    eng_name character varying(255) NOT NULL,
    rus_name character varying(255) NOT NULL,
    gender character varying(255) NOT NULL,
    is_gravid boolean DEFAULT false NOT NULL,
    min_age integer NOT NULL,
    max_age integer NOT NULL,
    min_value double precision NOT NULL,
    max_value double precision NOT NULL,
    units character varying(255) DEFAULT 'standart'::character varying NOT NULL
);


--
-- Name: indicator_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.indicator_group (
    id integer NOT NULL,
    group_name character varying(255) NOT NULL,
    indicators text[]
);


--
-- Name: indicator_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.indicator_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.indicator_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: indicator_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.indicator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.indicator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: measure; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.measure (
    id integer NOT NULL,
    person_id bigint NOT NULL,
    indicator_id integer NOT NULL,
    referent_id integer NOT NULL
);


--
-- Name: measure_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.measure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.measure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    gender character varying(255) NOT NULL,
    date_of_birth date NOT NULL,
    is_gravid boolean DEFAULT false NOT NULL
);


--
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: raise_reason; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.raise_reason (
    transcript_id integer NOT NULL,
    reason_id integer NOT NULL
);


--
-- Name: reason; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reason (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: reason_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reason ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reason_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referent (
    id integer NOT NULL,
    current_value double precision NOT NULL,
    reg_date date NOT NULL,
    status character varying(255) NOT NULL
);


--
-- Name: referent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.referent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.referent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: referent_transcript; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.referent_transcript (
    referent_id integer NOT NULL,
    transcript_id integer NOT NULL
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    customer_id bigint
);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transcript; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transcript (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    gender character varying(255) NOT NULL
);


--
-- Name: transcript_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transcript ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transcript_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit (
    id integer NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: unit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_token (
    token character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone,
    customer_id bigint
);


--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);


--
-- Name: excluded_reason excluded_reason_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.excluded_reason
    ADD CONSTRAINT excluded_reason_pkey PRIMARY KEY (person_id, reason_id);


--
-- Name: fall_reason fall_reason_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fall_reason
    ADD CONSTRAINT fall_reason_pkey PRIMARY KEY (transcript_id, reason_id);


--
-- Name: indicator_group indicator_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.indicator_group
    ADD CONSTRAINT indicator_group_pkey PRIMARY KEY (id);


--
-- Name: indicator indicator_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.indicator
    ADD CONSTRAINT indicator_pkey PRIMARY KEY (id);


--
-- Name: measure measure_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measure
    ADD CONSTRAINT measure_pkey PRIMARY KEY (id);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: raise_reason raise_reason_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raise_reason
    ADD CONSTRAINT raise_reason_pkey PRIMARY KEY (transcript_id, reason_id);


--
-- Name: reason reason_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reason
    ADD CONSTRAINT reason_pkey PRIMARY KEY (id);


--
-- Name: referent referent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referent
    ADD CONSTRAINT referent_pkey PRIMARY KEY (id);


--
-- Name: referent_transcript referent_transcript_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referent_transcript
    ADD CONSTRAINT referent_transcript_pkey PRIMARY KEY (referent_id, transcript_id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: transcript transcript_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transcript
    ADD CONSTRAINT transcript_pkey PRIMARY KEY (id);


--
-- Name: customer ukdwk6cx0afu8bs9o4t536v1j5v; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT ukdwk6cx0afu8bs9o4t536v1j5v UNIQUE (email);


--
-- Name: customer ukie7rkxg6fmtxx1aes55ox9yxd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT ukie7rkxg6fmtxx1aes55ox9yxd UNIQUE (person_id);


--
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- Name: verification_token verification_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT verification_token_pkey PRIMARY KEY (token);


--
-- Name: idx40l39kkkcn6q747ubmvel7onh; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx40l39kkkcn6q747ubmvel7onh ON public.reason USING btree (name);


--
-- Name: excluded_reason excluded_reason_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.excluded_reason
    ADD CONSTRAINT excluded_reason_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE CASCADE;


--
-- Name: excluded_reason excluded_reason_reason_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.excluded_reason
    ADD CONSTRAINT excluded_reason_reason_id_fkey FOREIGN KEY (reason_id) REFERENCES public.reason(id);


--
-- Name: fall_reason fall_reason_reason_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fall_reason
    ADD CONSTRAINT fall_reason_reason_id_fkey FOREIGN KEY (reason_id) REFERENCES public.reason(id);


--
-- Name: fall_reason fall_reason_transcript_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fall_reason
    ADD CONSTRAINT fall_reason_transcript_id_fkey FOREIGN KEY (transcript_id) REFERENCES public.transcript(id);


--
-- Name: verification_token fkmntaip7s5txf72u91b038pihm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_token
    ADD CONSTRAINT fkmntaip7s5txf72u91b038pihm FOREIGN KEY (customer_id) REFERENCES public.customer(id);


--
-- Name: customer fknvxfigj5o3te7ig37cq7qo0bc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT fknvxfigj5o3te7ig37cq7qo0bc FOREIGN KEY (person_id) REFERENCES public.person(id);


--
-- Name: refresh_token fkthlbvd34s3un1d4pxxqv2ni6c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkthlbvd34s3un1d4pxxqv2ni6c FOREIGN KEY (customer_id) REFERENCES public.customer(id);


--
-- Name: measure measure_indicator_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measure
    ADD CONSTRAINT measure_indicator_id_fkey FOREIGN KEY (indicator_id) REFERENCES public.indicator(id);


--
-- Name: measure measure_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measure
    ADD CONSTRAINT measure_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE CASCADE;


--
-- Name: measure measure_referent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.measure
    ADD CONSTRAINT measure_referent_id_fkey FOREIGN KEY (referent_id) REFERENCES public.referent(id) ON DELETE CASCADE;


--
-- Name: raise_reason raise_reason_reason_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raise_reason
    ADD CONSTRAINT raise_reason_reason_id_fkey FOREIGN KEY (reason_id) REFERENCES public.reason(id);


--
-- Name: raise_reason raise_reason_transcript_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.raise_reason
    ADD CONSTRAINT raise_reason_transcript_id_fkey FOREIGN KEY (transcript_id) REFERENCES public.transcript(id);


--
-- Name: referent_transcript referent_transcript_referent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referent_transcript
    ADD CONSTRAINT referent_transcript_referent_id_fkey FOREIGN KEY (referent_id) REFERENCES public.referent(id) ON DELETE CASCADE;


--
-- Name: referent_transcript referent_transcript_transcript_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.referent_transcript
    ADD CONSTRAINT referent_transcript_transcript_id_fkey FOREIGN KEY (transcript_id) REFERENCES public.transcript(id);

