CREATE TABLE "person"
(
    "id"            INTEGER PRIMARY KEY generated by default as identity,
    "name"          VARCHAR(255) NOT NULL,
    "gender"        VARCHAR(6)   NOT NULL,
    "date_of_birth" DATE         NOT NULL,
    "is_gravid"     BOOLEAN      NOT NULL DEFAULT false
);


CREATE TABLE "indicator"
(
    "id"        INTEGER PRIMARY KEY generated by default as identity,
    "eng_name"  VARCHAR(255) NOT NULL,
    "rus_name"  VARCHAR(255) NOT NULL,
    "gender"    VARCHAR(6)   NOT NULL,
    "is_gravid" BOOLEAN      NOT NULL DEFAULT false,
    "min_age"   INTEGER      NOT NULL,
    "max_age"   INTEGER      NOT NULL,
    "min_value" FLOAT(53)    NOT NULL,
    "max_value" FLOAT(53)    NOT NULL,
    "units"     VARCHAR(50)  NOT NULL DEFAULT 'standart'
);


CREATE TABLE "transcript"
(
    "id"     INTEGER PRIMARY KEY generated by default as identity,
    "name"   VARCHAR(255) NOT NULL,
    "gender" VARCHAR(6)   NOT NULL
);

CREATE TABLE "referent"
(
    "id"            INTEGER PRIMARY KEY generated by default as identity,
    "current_value" FLOAT(53)                                            NOT NULL,
    "reg_date"      DATE                                                 NOT NULL,
    "status"        VARCHAR(255)                                         NOT NULL,
    "transcript_id" INTEGER REFERENCES transcript (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE "reason"
(
    "id"   INTEGER PRIMARY KEY generated by default as identity,
    "name" VARCHAR(255) NOT NULL
);


CREATE TABLE fall_reason
(
    "transcript_id" INTEGER REFERENCES transcript (id) ON DELETE CASCADE,
    "reason_id"     INTEGER REFERENCES reason (id) ON DELETE NO ACTION,
    PRIMARY KEY ("transcript_id", "reason_id")
);

CREATE TABLE raise_reason
(
    "transcript_id" INTEGER REFERENCES transcript (id) ON DELETE CASCADE,
    "reason_id"     INTEGER REFERENCES reason (id) ON DELETE NO ACTION,
    PRIMARY KEY ("transcript_id", "reason_id")
);


CREATE TABLE "excluded_reason"
(
    "person_id" INTEGER REFERENCES Person (id) NOT NULL,
    "reason_id" INTEGER REFERENCES reason (id) NOT NULL,
    PRIMARY KEY ("person_id", "reason_id")
);


CREATE TABLE "measure"
(
    "id"           INTEGER PRIMARY KEY generated by default as identity,
    "person_id"    INTEGER REFERENCES Person (id)                     NOT NULL,
    "indicator_id" INTEGER REFERENCES Indicator (id)                  NOT NULL,
    "referent_id"  INTEGER REFERENCES Referent (id) ON DELETE CASCADE NOT NULL
);


